### ISSUE TITLE
Need to specify ruby version?

### ISSUE THREAD

**Issue by DerekKaknes** [learn-co-curriculum/rails-layouts-and-templates-lab#10]
I think that there are some incompatibilities between ruby-2.4.X and the gem json-1.8.X that comes in rails-4.2.5.  I get an error about building native extensions when trying to bundle or gem install that json package.  My solution was to revert to using ruby-2.2.X, after which everything worked fine.  It might be worth specifying the ruby version requirements in the Gemfile so that users get a more clear error when trying to bundle with an incompatible version.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
