### ISSUE TITLE
Bundler could not find compatible versions for gem "activesupport"

### ISSUE THREAD

**Issue by akedalat** [learn-co-curriculum/rails-layouts-and-templates-lab#12]
Usually, this issue will solve by adding Gemfile.lock from other repositories but I can't get around this one! 
Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (= 5.2.2)

  In Gemfile:
    rails (~> 4.2) was resolved to 4.2.1.rc1, which depends on
      activesupport (= 4.2.1.rc1)

    sass-rails (~> 5.0) was resolved to 5.0.7, which depends on
      railties (>= 4.0.0, < 6) was resolved to 5.2.2, which depends on
        activesupport (= 5.2.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by maxwellbenton** [comment]
HI @akedalat,

Thank you for spotting this. I was able to replicate the issue you were having, fixed it by adding a Gemfile.lock this repo and believe your issue to be resolved. If you are still working on this lesson and would like to use the updated version, you may need to delete your personal fork of the repo and revisit the lesson on learn.co to access the content.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
