### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ode-to-the-code** [learn-co-curriculum/rails-layouts-and-templates-lab#13]
I don't know if this is deliberate but it seems like a typo saying 'in' instead of 'for'-

Create a home view **in** StoreAdminController with an h2 that says "Welcome Flatiron Admin".

**Comment by maxwellbenton** [comment]
Hi @ode-to-the-code,

Thanks for pointing this out! We've fixed the typo so future students will see the corrected content. Thanks for contributing to a learn.co lesson!

**Comment by ode-to-the-code** [comment]
Sure thing Maxwell
