### ISSUE TITLE
Deprecated code in test specs

### ISSUE THREAD

**Issue by dougschallmoser** [learn-co-curriculum/rails-layouts-and-templates-lab#21]
When tests are run, there are several lines of code that are deprecated. It doesn't seem to affect the ability to pass the tests though. See error messages below when 'learn' is executed in the terminal.

DEPRECATION WARNING: `config.serve_static_files` is deprecated and will be removed in Rails 5.1.
Please use `config.public_file_server.enabled = true` instead.
 (called from block in <top (required)> at /Users/dougschallmoser/Development/flatiron/labs/rails-layouts-and-templates-lab-onl01-seng-ft-070620/config/environments/test.rb:16)
DEPRECATION WARNING: `config.static_cache_control` is deprecated and will be removed in Rails 5.1.
Please use
`config.public_file_server.headers = { 'Cache-Control' => 'public, max-age=3600' }`
instead.
 (called from block in <top (required)> at /Users/dougschallmoser/Development/flatiron/labs/rails-layouts-and-templates-lab-onl01-seng-ft-070620/config/environments/test.rb:18)
DEPRECATION WARNING: ActiveRecord::Base.raise_in_transactional_callbacks= is deprecated, has no effect and will be removed without replacement. (called from <top (required)> at /Users/dougschallmoser/Development/flatiron/labs/rails-layouts-and-templates-lab-onl01-seng-ft-070620/spec/rails_helper.rb:27)
DEPRECATION WARNING: `config.serve_static_files` is deprecated and will be removed in Rails 5.1.
Please use `config.public_file_server.enabled = true` instead.
 (called from block in <top (required)> at /Users/dougschallmoser/Development/flatiron/labs/rails-layouts-and-templates-lab-onl01-seng-ft-070620/config/environments/test.rb:16)
DEPRECATION WARNING: `config.static_cache_control` is deprecated and will be removed in Rails 5.1.
Please use
`config.public_file_server.headers = { 'Cache-Control' => 'public, max-age=3600' }`
instead.
 (called from block in <top (required)> at /Users/dougschallmoser/Development/flatiron/labs/rails-layouts-and-templates-lab-onl01-seng-ft-070620/config/environments/test.rb:18)
DEPRECATION WARNING: ActiveRecord::Base.raise_in_transactional_callbacks= is deprecated, has no effect and will be removed without replacement. (called from require at /Users/dougschallmoser/Development/flatiron/labs/rails-layouts-and-templates-lab-onl01-seng-ft-070620/bin/rails:9)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thanks for contributing to the Flatiron curriculum! 💙
