### ISSUE TITLE
gem needed to run tests

### ISSUE THREAD

**Issue by wlytle** [learn-co-curriculum/rails-layouts-and-templates-lab#22]
It appears some of the tests won't run without adding gem 'rails-controller-testing' to the gemfile

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thanks for contributing to the Flatiron curriculum! 💙
