### ISSUE TITLE
Erroneous warning about not having completed a lesson

### ISSUE THREAD

**Issue by jonbf** [learn-co-curriculum/rails-layouts-and-templates-lab#9]
If you complete a lesson (e.g., for a lab, fork, pass all tests and submit), but then break some tests, and then click "next lesson", you get an erroneous warning that you have not completed the lesson.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a bug in the Learn platform.
[Raising issues on
GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson)
should be reserved for problems with the curriculum itself (doesn't work,
throws a Ruby error, etc.)

You can reach our product team at support@learn.co. Alternatively, if Learn
is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
